name: Publish Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
      - "bifrost-*"
    tags:
      - "v*"

permissions: write-all

jobs:
  push_to_registry:
    if: github.repository == 'diogo464/go-ipfs' || github.event_name == 'workflow_dispatch'
    name: Push Docker image to Github Container Registry
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/diogo464/kubo
      LEGACY_IMAGE_NAME: ghcr.io/diogo464/go-ipfs
    strategy:
      fail-fast: true
      matrix:
        platform: [linux/amd64, linux/arm64, linux/arm/v7]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get tags
        id: tags
        run: |
          TAGS="$(./bin/get-docker-tags.sh $(date -u +%F))"
          TAGS="${TAGS//$'\n'/'%0A'}"
          echo "::set-output name=value::$(echo $TAGS)"
        shell: bash

      - name: Build Docker image and publish to Github container registry
        uses: docker/build-push-action@v2
        with:
          platforms: ${{ matrix.platform }}
          context: .
          push: true
          file: ./Dockerfile
          tags: "${{ steps.tags.outputs.value }}"
